// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGQ-WYz5ra4j5cSiR-TSiRSohBKR8_Xx0',
    appId: '1:713063293671:web:02a67181c86caf248c7842',
    messagingSenderId: '713063293671',
    projectId: 'fiesto-flutter-app',
    authDomain: 'fiesto-flutter-app.firebaseapp.com',
    storageBucket: 'fiesto-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmE9vSXVV4cJrHbNak67bWr8ewRzUSmXc',
    appId: '1:713063293671:android:23e63fceeba874338c7842',
    messagingSenderId: '713063293671',
    projectId: 'fiesto-flutter-app',
    storageBucket: 'fiesto-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2jMhTWaA_9Rocm1szbykJ_gdQoUgktts',
    appId: '1:713063293671:ios:050a5df9a02d371d8c7842',
    messagingSenderId: '713063293671',
    projectId: 'fiesto-flutter-app',
    storageBucket: 'fiesto-flutter-app.appspot.com',
    iosClientId: '713063293671-ip1pgib2to9l51bmrppl5rcsuv4edb68.apps.googleusercontent.com',
    iosBundleId: 'in.fiesto.fiesto',
  );
}
